create table tb_owner (id bigint generated by default as identity, email varchar(255), name varchar(255), phone varchar(255), primary key (id));
create table tb_tenant (id bigint generated by default as identity, email varchar(255), name varchar(255), phone varchar(255), primary key (id));
create table tb_user (id bigint generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
